namespace DarwinLingua.WebApi.Persistence.Entities;

/// <summary>
/// Represents one server-side content import and package publication receipt.
/// </summary>
public sealed class ContentImportReceiptEntity
{
    /// <summary>
    /// Gets or sets the primary key.
    /// </summary>
    public Guid Id { get; set; }

    /// <summary>
    /// Gets or sets the target client-product key.
    /// </summary>
    public string ClientProductKey { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the imported file path.
    /// </summary>
    public string SourceFilePath { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the source file name.
    /// </summary>
    public string SourceFileName { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the imported package identifier.
    /// </summary>
    public string? ImportedPackageId { get; set; }

    /// <summary>
    /// Gets or sets the imported package name.
    /// </summary>
    public string? ImportedPackageName { get; set; }

    /// <summary>
    /// Gets or sets the import status.
    /// </summary>
    public string ImportStatus { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the total entry count.
    /// </summary>
    public int TotalEntries { get; set; }

    /// <summary>
    /// Gets or sets the inserted entry count.
    /// </summary>
    public int ImportedEntries { get; set; }

    /// <summary>
    /// Gets or sets the duplicate entry count.
    /// </summary>
    public int SkippedDuplicateEntries { get; set; }

    /// <summary>
    /// Gets or sets the invalid entry count.
    /// </summary>
    public int InvalidEntries { get; set; }

    /// <summary>
    /// Gets or sets the warning count.
    /// </summary>
    public int WarningCount { get; set; }

    /// <summary>
    /// Gets or sets the short issue summary.
    /// </summary>
    public string IssueSummary { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the number of packages generated by the publish step.
    /// </summary>
    public int PublishedPackageCount { get; set; }

    /// <summary>
    /// Gets or sets the published package identifiers.
    /// </summary>
    public string PublishedPackageIds { get; set; } = string.Empty;

    /// <summary>
    /// Gets or sets the UTC creation timestamp.
    /// </summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>
    /// Gets or sets the UTC last update timestamp.
    /// </summary>
    public DateTimeOffset UpdatedAtUtc { get; set; }
}
