#!/bin/bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
DO
\$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DARWINLINGUA_POSTGRES_APP_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${DARWINLINGUA_POSTGRES_APP_USER}', '${DARWINLINGUA_POSTGRES_APP_PASSWORD}');
    END IF;
END
\$\$;

DO
\$\$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${DARWINLINGUA_POSTGRES_ADMIN_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${DARWINLINGUA_POSTGRES_ADMIN_USER}', '${DARWINLINGUA_POSTGRES_ADMIN_PASSWORD}');
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${DARWINLINGUA_POSTGRES_DB} TO ${DARWINLINGUA_POSTGRES_APP_USER};
GRANT CONNECT ON DATABASE ${DARWINLINGUA_POSTGRES_DB} TO ${DARWINLINGUA_POSTGRES_ADMIN_USER};

GRANT USAGE ON SCHEMA public TO ${DARWINLINGUA_POSTGRES_APP_USER};
GRANT USAGE, CREATE ON SCHEMA public TO ${DARWINLINGUA_POSTGRES_ADMIN_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DARWINLINGUA_POSTGRES_ADMIN_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO ${DARWINLINGUA_POSTGRES_APP_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO ${DARWINLINGUA_POSTGRES_ADMIN_USER};

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON SEQUENCES TO ${DARWINLINGUA_POSTGRES_APP_USER};
EOSQL
