namespace DarwinLingua.ContentOps.Application.Models;

public sealed record ParsedWritingTemplateModel(
    string Slug,
    string Title,
    IReadOnlyList<ParsedContentMeaningModel> TitleTranslations,
    string ShortDescription,
    IReadOnlyList<ParsedContentMeaningModel> ShortDescriptionTranslations,
    string CefrLevel,
    string Category,
    string Situation,
    IReadOnlyList<ParsedContentMeaningModel> SituationTranslations,
    string Register,
    string TemplateText,
    IReadOnlyList<ParsedContentMeaningModel> TemplateTextTranslations,
    string Explanation,
    IReadOnlyList<ParsedContentMeaningModel> ExplanationTranslations,
    IReadOnlyList<string> ReplaceableVariables,
    string SampleFilledVersion,
    IReadOnlyList<ParsedContentMeaningModel> SampleFilledVersionTranslations,
    IReadOnlyList<string> LinkedGrammarTopicSlugs,
    IReadOnlyList<string> LinkedWordSlugs,
    IReadOnlyList<string> LinkedExpressionSlugs,
    IReadOnlyList<string> LinkedExerciseSlugs,
    IReadOnlyList<string> LinkedCourseLessonSlugs,
    bool IsPublished,
    int SortOrder);
