// <auto-generated />
using DarwinLingua.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DarwinLingua.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(DarwinLinguaDbContext))]
    [Migration("20260525120000_AddExpressionSensitiveEducationalLanguageMetadata")]
    partial class AddExpressionSensitiveEducationalLanguageMetadata
    {
    }
}
